# Generated by Django 3.2 on 2021-04-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AccountType',
            field=models.CharField(choices=[('fund_accounts', 'FundAccounts'), ('tranfer_accounts', 'TranferAccount'), ('commission_accounts', 'CommissionAccounts')], default='fund_accounts', max_length=20),
        ),
    ]
