# Generated by Django 3.1.5 on 2021-02-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='describtion',
            new_name='description',
        ),
    ]
