# Generated by Django 3.2 on 2021-04-24 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0002_auto_20210424_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.AddField(
            model_name='transfer',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='ExpressNo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='Purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='ReceiverName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='Region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='SenderName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='direction',
            field=models.IntegerField(choices=[(-1, 'send'), (1, 'recieve')]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='tr_hash',
            field=models.UUIDField(default=uuid.UUID('ce332ffe-3e75-4074-803b-646e3592f14c')),
        ),
    ]
