# Generated by Django 3.2 on 2021-04-24 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0003_auto_20210425_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='tr_hash',
            field=models.UUIDField(default=uuid.UUID('b66b9e10-38a2-4972-b7be-00b2e748437c')),
        ),
    ]
