# Generated by Django 3.2 on 2021-04-24 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0004_alter_transfer_tr_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='tr_hash',
            field=models.UUIDField(default=uuid.UUID('015e0d33-26f6-4a1a-ab86-d10548db7473')),
        ),
    ]
